### ISSUE TITLE
anything starting with p in a line will not render the first 3 chars

### ISSUE THREAD

**Issue by naciron** [borgar/textile-js#21]
Anytime I start writing a line starting with "p" like "posted a new issue" the first 3 chars will not be shown in the outsome. So in that example only "ted a new issue" is rendered".

This happens in the demo, too.
![screen shot 2015-01-08 at 12 05 38](https://cloud.githubusercontent.com/assets/10449201/5662258/b8173338-972e-11e4-84a1-21fe3b49f9a4.png)

**Comment by borgar** [comment]
I am unable to reproduce this. Could you please provide details of your setup (browser, browser version, and OS)?

**Comment by naciron** [comment]
It happens to me in your live demo as seen on the screenshot when I e.g. enter the word "posted" after the first headline. If I write "p. posted" instead then it works.

Browsers: 
- Mac OS, Chrome 39.0.2171.95 (64-bit)
- Mac OS, Safari 8
- Mac OS, Firefox 34
- Android, Chrome
- Android, Firefox

**Comment by borgar** [comment]
Ok, I've finally managed to reproduce the issue. It seems to happen only when these paragraphs are followed by a line ending in a `". "` (period, space).

So this will trigger it:

    pos\n
    \n
    posted\n
    \n
    You can just write the text you like.\s

But this will not.

    pos\n
    \n
    posted\n
    \n
    You can just write the text you like.

So no wonder I couldn't reproduce it initially as I was unable to see the invisible trailing space there. :confounded:

**Comment by borgar** [comment]
All better now! Thanks for reporting.
