### ISSUE TITLE
Publish 0.1.11 on NPM?

### ISSUE THREAD

**Issue by bensheldon** [borgar/textile-js#22]
Could you please publish the latest version to NPM? Currently NPM's version is `0.1.10`. Thank you!

**Comment by borgar** [comment]
Whoops! Sorry, must have forgot this last time I pushed. All fixed now. Thanks for the nudge!

**Comment by bensheldon** [comment]
Thanks! 

Also, I'm trying to use it now with Bower. It seems like Bower expects versions to be git tags. I'm able to lock it to the SHA, but but they want explicit tagged releases in order to use the version argument in the bower.json file. http://bower.io/docs/creating-packages/#register

> Your package should use semver Git tags.

**Comment by borgar** [comment]
Ok, I *think* I've set this up correctly now. There is now [a version tag for the current version](https://github.com/borgar/textile-js/tree/v0.1.11) so hopefully things work as expected. If not, then just give me nudge.

I've also taken the time to automate the bower/npm publishing process to try to ensure that this keeps working from now on.
