### ISSUE TITLE
Add html 5 video 

### ISSUE THREAD

**Issue by neonnds** [borgar/textile-js#24]
As html5 video is supported on modern browsers is it possible to implement an additional tag allowing video.

For example: 

```
!movie.mp4,movie.ogg:320,240!
```

Would render as:

```
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
```

**Comment by borgar** [comment]
Is this supported by any other Textile implementation?

**Comment by neonnds** [comment]
I'm not aware of markdown etc having it. Just seems like a natural progression, considering we already allow images.

**Comment by borgar** [comment]
Evolution of the textile language is done by the [textile-php guys](https://github.com/textile/php-textile). Textile-js is only a single implementation of many of the language. As such my primary goal is to be compatible with what is already out there and avoid fragmenting the landscape.

The correct way to get HTML5 media elements support is by [filing a feature request ticket with php-textile](https://github.com/textile/php-textile/issues) and then it will eventually get support here too (tag me if you do create a ticket over there).

I do see the value in the request. But I will decline adding features not commonly supported by other flavours of textile (specifically the RedCloth and PHP versions).

That being said, I have considered the option of making the parser pluggable so users may add features as they need. Suggestions to how such an interface might look are welcome.
