### ISSUE TITLE
Support Internet Explorer 8

### ISSUE THREAD

**Issue by adammessinger** [borgar/textile-js#25]
I'd like to use this in a product that still needs to support IE 8 (I know, I know), but the script doesn't work there. The use of `array.forEach()` seems to be what's causing problems there.

**Comment by borgar** [comment]
I don't really have the stomach to un-JS1.8-ify the code (it's already rather obtuse). 

If this were me, I would just assemble the polyfills for the missing method into a separate file and include that in the IE8 deployment. They are (at least): [Array#map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Polyfill), [Array#filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Polyfill), [Array#forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill), and [String#trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim#Polyfill).

The real fear I have with supporting IE8 is that RegExp behaviour may be subtly different and that may end up as the biggest problem with supporting it. Including polyfills and running unit tests would be a first step in determining what the effort is.

I don't have the time to chase this right now but would appreciate any info/feedback into this ticket.

**Comment by adammessinger** [comment]
Thanks for the polyfill list. Loading the recommended polyfills for browsers that don't support those methods seems to do the trick, with one exception I've noticed so far. Trying to include an ordered list as the child of a `<li>` in an _unordered_ list results in a nested unordered list instead. So, for example, this:

```
* uno
* dos
## one
## two
## three
* tres
```

Produces this output:

```html

<ul>
  <li>uno</li>
  <li>dos 
    <ul>
      <li>one</li>
      <li>two</li>
      <li>three</li>
    </ul>
  </li>
  <li>tres</li>
</ul>
```

Going about it the other way around -- an `<ol>` nested in an `<ul>` -- works fine. Could this be due to the kind of subtle regex problem your were worried about?

**Comment by borgar** [comment]
Yeah, this is exactly the kind of thing I was worried about might happen. Although this might not necessarily be a RegExp thing, it's exactly the sort of sneaky stuff the engine throws at us.

**Comment by borgar** [comment]
I think we should all just try to accept that this is never going to happen and say goodbye to the beautiful dream, such as it was, to run textile-js in IE8.
