### ISSUE TITLE
Bug with italic font

### ISSUE THREAD

**Issue by Lol9tor** [borgar/textile-js#29]
When you write some text like that: 
<pre>_Some italic text_</pre> 
it transform to italic, but it you write something like that:
<pre>_Some multiline text
and another line_</pre> 
it doesn't transform, but have to. I checked it on http://redcloth.org/

P.S. It don't have to more than 1 new line character between lines with italic font

**Comment by borgar** [comment]
Sorry, but this is the expected behaviour. RedCloth is wrong here. [The PHP implementation](http://txstyle.org/doc), which I consider authoritative variant in most cases, does not allow phrasing around line-breaks so neither will *textile-js*.
