### ISSUE TITLE
Mixed list style resolution

### ISSUE THREAD

**Issue by borgar** [borgar/textile-js#33]
Given the markup:

    # foo
    # bar
    * baz

We output the following HTML:

    <ol>
        <li>foo</li>
        <li>bar</li>
        <li>baz</li>
    </ol>

This is consistent with what RedCloth does but not what PHP does. The PHP implementation does this:

    <ol>
        <li>foo</li>
        <li>bar</li>
    <ul>
        <li>baz</li>
    </ul>
    </ol>

This is obviously not what [anyone expects to happen](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), and it is doubtful, given that this isn't [valid HTML](https://www.w3.org/TR/html5/grouping-content.html#the-ol-element) and renders as nested lists:

1. foo
1. bar
  * bas

A better output might look like this:

    <ol>
        <li>foo</li>
        <li>bar</li>
    </ol>
    <ul>
        <li>baz</li>
    </ul>

Which would be consistent with how lists are treated as blocks even if the are not preceded with double linebreaks:

    Some text
    * foo
    * bar
    * baz

(See issues #30 and #18.)

**Comment by borgar** [comment]
Seeing as PHP is broken and effectively prevents people from using mixed syntax, and we do the same thing RedCloth does. I am not inclined to "fix" this. Also because list parsing is already very complicated.

**Comment by kpym** [comment]
You should probably fix the online version (gh-pages) too ;)
