### ISSUE TITLE
Center alignment for images

### ISSUE THREAD

**Issue by kpym** [borgar/textile-js#35]
The syntaxes `!>...!` and `!<...!` works well for images by translating them to `float`.

But `!=...!` is not working properly because it translates to `align="center"` which is a vertical and not horizontal align. Probably a best option will be to translate it to

    style="display:block; margin-left:auto; margin-right: auto;"

**Comment by borgar** [comment]
I know `align="center"` doesn't make any sense. More insanely, `align="center"` doesn't even exist on images in HTML. The correct horizontal alignment attribute on `img` tags is `align="middle"`. I think this exists on images simply to keep consistency to text alignment on other block level elements (`div`, `p`) .

[txstyle.org](http://txstyle.org/doc/24/text-alignment) even goes as far as to recommend an alternative:

> [...] for centering images, the preferred method is to use CSS:
>
>     !{display:block; margin-left:auto; margin-right:auto;}/img/carver.jpeg!

I think a much better way to achieve a centered image this would be something like this:

    div=. !/img/carver.jpeg!

In any case, this is what the textile spec says should happen and the other implementations comply with so I'm declining this for compatibility reasons.
