### ISSUE TITLE
Nested blockquotes?

### ISSUE THREAD

**Issue by Ruudiluca** [borgar/textile-js#36]
Blockquotes inside blockquotes don't seem to be appearing as blockquotes. Could this be worked on?

**Comment by borgar** [comment]
As far as I know the Textile spec does not support nested blockquotes. What would be the syntax or an example of this?

**Comment by Ruudiluca** [comment]
My apologies, I am referring to the HTML version of blockquotes.
When using nested `<blockquote>` tags in textile-js, it does not show the nested blockquotes properly. This is because it is transforming the < and > symbols into &lt; &gt; text.

**Comment by borgar** [comment]
Aha, I get it. Quick testing confirms that this is indeed a bug.

The following should flow unchanged through the parser but instead escapes the inner tags.

```
<div>foobar</div>

<div>a<div>b</div>c</div>

<blockquote>a</blockquote>

<blockquote>a<blockquote>b</blockquote>c</blockquote>
```

**Comment by borgar** [comment]
I've looked at the code and have come across this comment in the code:

> Unsurprisingly, all Textile implementations I have tested have trouble parsing simple HTML.
> I simply match them here as there is no way anyone is using nested HTML today, or if they
> are, then this will at least output less broken HTML as redundant tags will get quoted.

Looks like this is what we're hitting and time has caught up with me here. Time to fix this...

**Comment by Ruudiluca** [comment]
Excellent. Thanks for looking into it.
