### ISSUE TITLE
Browser CPU Lockup

### ISSUE THREAD

**Issue by bensheldon** [borgar/textile-js#40]
I've discovered that certain strings of text will lock up the browser window when running `textile.parse()` upon that string. It seems to be triggered when parsing something that looks like this `!x(yyyyyyyyy)` in which `x` is any character and `yyyy` is a long string. The regexp would be:

```regexp
 /\![^\s].*\(.*\)/ 
```

For example, `!a (ABCDEFGHIJ_ABCDEFGHIJ)` will freeze up the browser window for several seconds if pasted into http://borgar.github.io/textile-js/ (you may need to clear localstorage to continue using that page). Adding additional text within the enclosing parenthesis will lead to longer lockups.

You may think "who would type that?", but for example this snippet of escaped PHP code will cause a lockup: `(!isset($_SERVER[&#x27;HTTP_X_SSL&#x27;])`.

I'm not really sure of the best way to further investigate or suggest a fix, but I'd be happy to help.

**Comment by bensheldon** [comment]
I just found another example that doesn't require the closing quote:

`!@((. tset Sûpp0rt ticket onññly... !@((. tset Sûpp0rt ticket onññly... !@((.`

...the things people come up with 😄

**Comment by borgar** [comment]
I've looked at this and it turns out that this is the image matching regexp causing problems. I've already fixed pretty much the exact same scenario in issue #20. I have a fix ready and will push an update in the next hour or so.

**Comment by borgar** [comment]
I have pushed a new version to npm and updated the test page with the fix. All should be better now. 😎

**Comment by bensheldon** [comment]
Woohoo! 🙇  thanks.
