### ISSUE TITLE
Self referencing link "$":link

### ISSUE THREAD

**Issue by cmroanirgo** [borgar/textile-js#44]
The [textpatten docs](https://txstyle.org/doc/12/links) indicate the following is a valid markup:

> 5) If you wish to link to a URL and want the URL itself in the text, you can use the following “dollar” shorthand:
> 
> `"$":http://example.com/sw`
> 
> (The above link was slightly changed by me)

Unfortunately, this api doesn't allow it, and renders it as:

`<a href="http://example.com/sw">$</a>`

I expected:

`<a href="http://example.com/sw">http://example.com/sw</a>`

Thanks for a great textile api however! I've been using various versions for quite some time now 👍

**Comment by borgar** [comment]
This should be simple to add. The only reason it isn't in there already is that I've never seen it before. 😅  I assume it is a "fairly recent" addition (RedCloth doesn't know how to do this and it wasn't there when I did the initial port).

I'll take a look when I can find the time.

**Comment by cmroanirgo** [comment]
Yes, it's new to me too. What would *actually* be awesome is the automagic recognition of a bare url:

https://some.example.com/folder/

...like markdown extensions do. 

I'm not sure if you're interested in that kind of thing however.

I have another suggestion along that line too: eg `/some/image/file.jpg` should automatically be changed to an `<img src='/some/image/file.jpg' />` ... ;)

I find textile so naturally awesome to write in: except bare urls and simple images (not that images are hard,really) ;) 

I'm in no rush for changes btw. What you've done already is pretty awesome, and as you said, I used to follow the RedCloth version as well.

**Comment by borgar** [comment]
Yeah, I don't know why Textile doesn't support this by default. My current line is to try to follow the spec/PHP implementation as closely as I can _by default_. There is nothing wrong with having and allowing this behaviour with flags though.

I have been considering adding some sort of callback hooks/transformers for nodes and attributes. Partly to ease solving things like the issue in #42. Having that, it would be simple to bundle a few built in transformers and allow quickly enabling them with flags.

**Comment by cmroanirgo** [comment]
Many thanks @borgar!
