### ISSUE TITLE
Missing Table variables

### ISSUE THREAD

**Issue by B14d3r11** [borgar/textile-js#48]
When making a table if you use 

`/2.| Words |`
or  
`\2.| Words |`

This would make the table span 2 rows or 2 columns. This isn't in your visual editor yet sadly. Just though i'd let you know

**Comment by borgar** [comment]
Both colspan and rowspan for table cells are supported by textile-js and all [examples on the txstyle.org website](https://txstyle.org/doc/15/tables) render perfectly as far as I know. 

Either you have found a specific bug, in which I need code to reproduce that, or you are simply using wrong syntax. The examples given are not valid textile and should be:

`|/2. Words |`

and/or

`|\2. Words |`
