### ISSUE TITLE
Vertical align broken

### ISSUE THREAD

**Issue by MaximusFT** [borgar/textile-js#50]
This sample text is broken.
If not use vertical-align (in `|^. Intro |` without `^.`) then all works well...
If remove `\n` in text => `elit. Sed`... then all works well...
But if you need a new line in table cell...

```
|^. 
|_. Feature | Description |
|-.
|^. Intro | Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Sed ullamcorper justo et luctus venenatis.|
```

**Comment by borgar** [comment]
I can take a look at this. But, be advised that your example isn't valid Textile markup. Textile does not support line-breaking in tables (I know my implementation supports it to a degree, but this isn't the standard).

You can try your example at https://txstyle.org/, the reference implementation, and see it fail there too.

Both implementations to the same thing with the "standard" way of writing this, which is:

```
|^. 
|_. Feature | Description |
|-.
|^. Intro | Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br><br>Sed ullamcorper justo et luctus venenatis.|
```

**Comment by MaximusFT** [comment]
Yes... with html tag <br> it's work. Thanks
