### ISSUE TITLE
Garbage not reduced correctly after a table

### ISSUE THREAD

**Issue by GehDoc** [borgar/textile-js#52]
Garbage reduction is broken, when more than 1 empty line after a table.

**Exemple 1, with 2 empty lines :** the header is not formatted.

```textile
|a|b|


h1. header
```

Output :

```html
<table>
	<tr>
		<td>a</td>
		<td>b</td>
	</tr>
</table>
h1. Test
```

**Exemple 2, with 3 empty lines :** the header is formatted, but an empty paragraph is inserted.

```textile
|a|b|



h1. header
```

Output :

```html
<table>
	<tr>
		<td>a</td>
		<td>b</td>
	</tr>
</table>
<p></p>
<h1>Test</h1>
```

**Comment by GehDoc** [comment]
Hi @borgar ,

Can take a look at this commit in my repo ? GehDoc/textile-js@071a1d3
It fixes this bug, and doesn't break any exiting test.

**Comment by borgar** [comment]
This is definitely something I want to look at but I have not had the time to yet. Sorry for the delay. Hopefully soon! 🙂
