### ISSUE TITLE
Not sure if this regex does what you want

### ISSUE THREAD

**Issue by LouisMichael** [borgar/textile-js#54]
I was looking through some project regex and found this one [here](https://github.com/borgar/textile-js/blob/09339bde59d3360fe4e2bbf1da908629d9d6d7fd/src/textile/phrase.js#L34). Testing it I found that it accepts `u]:1]]` note all of the odd ].
This is because javascript does not support POSIX Bracket Expressions the way some regex languages do and instead ended character classes at odd times with sets that may not be intended.

**Comment by borgar** [comment]
I think you missed the part where the regex is passed through `re.compile` and the bracket expressions are rewritten to JS compatible regexp.
