### ISSUE TITLE
*foo*<notextile></notextile>bar should result in concatenated output foobar

### ISSUE THREAD

**Issue by level420** [borgar/textile-js#57]
Evaluation textile.js version 2.0.4.

As there is no possibility to concatenate a bold word with a non bold word, we are using the sequence
```
*foo*<notextile></notextile>bar
```
to get the result **foo**bar.

Obviously textile.js does not tokenize the source text correctly for the starting `*foo*` in this case.

**Comment by borgar** [comment]
I agree that your example should work.

In the meantime Textile-js does support fences, which is the recommended way to do this. So you can work around this with `[*foo*]bar` if you need this asap.

**Comment by level420** [comment]
Thank you @borgar@. Yes fences work in textile.js. But I need to convert textile markup which is written in redmine textile, where fences are not available.

Do you have any schedule for a bug fix? Would be great to have this fixed.

**Comment by borgar** [comment]
This should be fixed and released.

**Comment by level420** [comment]
Thank you @borgar! Great works like a charm.
It's available on npm https://www.npmjs.com/package/textile-js
But there is no release 2.0.5 tag on github release tab https://github.com/borgar/textile-js/releases (don't know if it should though).
