### ISSUE TITLE
links are not correctly parsed when preceded by certain symbols

### ISSUE THREAD

**Issue by kpym** [borgar/textile-js#60]
If we have `(` just before a link like in `("link":url.com` it is parsed correctly as `(<a href="url.com">link</a>`.

But when the symbol is different, like `[`, `<`, `%`..., this breaks the link parsing. 
For example `["link":url.com` is parsed as `[&#8220;link&#8221;:url.com` in place of the expected `[<a href="url.com">link</a>`.

I discovered this by trying to put an email as follows:
```
John <"john@url.org":mailto:john@url.org>
```
which was interpreted as 
```
John &lt;&#8220;john@url.org&#8221;:mailto:john@url.org&gt;
```

To get around this bug we can replace the symbol by its html code, for example 
```
John &lt;"john@url.org":mailto:john@url.org>
```
which produce the desired
```
John &lt;<a href="mailto:john@url.org">john@url.org</a>&gt;
```
John &lt;<a href="mailto:john@url.org">john@url.org</a>&gt;

**Comment by Nixon-Joseph** [comment]
I've run into this as well. Temporarily changing to the `textilejs` npm package [here](https://www.npmjs.com/package/textilejs). It's much older, and doesn't have recent updates, but seems to parse properly with all the tests I've thrown at it. I will be following this thread in hopes it gets fixed.
