### ISSUE TITLE
Table header row is always centered horizontally

### ISSUE THREAD

**Issue by Nabav** [borgar/textile-js#89]
Also reported in https://github.com/GehDoc/textile-js/issues/6.

**Describe the bug**
The cells of the first row of a table are centered disregarding formatting characters.

**To Reproduce**
Use this and preview:

```textile
|_. Col1          |_=. Col2        |_.  Col3          |
|=.  col1 row1    |   col2 row1    |=.  col3 row1     |
|=.  col1 row end |   col2 row end |=.  col3 row end  |
```

**Expected behavior**
As rendered by textile-lang.com, just the second column is centered as specified by `_=.`, the other two columns are not centered horizontally in the first row.

![image](https://github.com/GehDoc/vscode-textile-preview/assets/24389873/e5910559-9087-4b63-8e7c-8ebd263ef7b7)

**Additional context**
This is what is currently rendered in live web editor:

![image](https://github.com/borgar/textile-js/assets/24389873/78958933-a272-4f47-bf7d-56b46e9f0937)

**Comment by borgar** [comment]
If you check the HTML Output tab of the web editor you can see that the HTML generated is identical to the output from textile-lang.com.

The problem is that browser default styles use centered for all `<th>` elements. You will need to provide a reset CSS to counter this.
